#!/bin/sh

./scripts/set_crontab
if [ $USER_ID ] && [ $GROUP_ID ]
then
    addgroup -g $GROUP_ID docker
    adduser -D -H -u $USER_ID -G docker docker
    export RUNAS_USER=1
fi
./scripts/sync_mirror &
nginx